language: python
python:
  - "3.3"
  - "3.4"
  - "nightly"
# command to install dependencies
install:
  - "pip install ."
  - "pip install -r requirements-headless.txt"
# command to run tests
script: nosetests
